### ISSUE TITLE
I'd like to make a front-end page for this page.

### ISSUE THREAD

**Issue by seanoh1989** [iCHAIT/awesome-osx#134]
The address could be simply `awesome-osx.github.io` or something like that whatever the repo owner decides to.

The website can be a `Bootstrap` single page with Jumbotron for header,

and multiple table rows and columns consists of each product. Once user clicks, it will show a `modal` so the user can stick with the same page. 

I have my portfolio website (still under development :p ) at http://saehunseanoh.me and it will look similar to Project section. 

anyone interested? then I'll start it from today.

**Comment by iCHAIT** [comment]
@seanoh1989 Hi

I totally like the idea of a web page for the list, was myself interested in making one but couldn't start with it due to lack of time. Though I would reckon before you start off with it, it would be nice to have feedback and suggestion particularly on the design of the page, from other developers.

@dufferzafar @herrbischoff

**Comment by seanoh1989** [comment]
@iCHAIT complete source code of my web is viewable [here](https://github.com/seanoh1989/seanoh1989.github.io) and my website framework is inspired by [Freelanceer](http://startbootstrap.com/template-overviews/freelancer/) with multiple other libraries like Hover.css.

For the images, I used [pixrl](https://pixlr.com/editor/) and I saved the templete. So it will be easy next time I want to create an image for the projects. And I can absolutely provide that.

Let me know :)

**Comment by dufferzafar** [comment]
@seanoh1989 Cool Portfolio.

I'd :+1: this.

**Comment by herrbischoff** [comment]
I would keep the site as simple as possible, without any modals, "jumbotrons" or other gimmicks. Bootstrap sounds like the popular go-to framework but it's a pain to modify the components since you need to overwrite the defaults in dozens of places or start meddling with the source files themselves. For me, Bootstrap is a nice solution for quick web **apps** but not necessarily for websites. I my experience it's more often trouble than not in the long run. Just my two cents.

Also you'd probably need to leverage a JS Markdown parser, like this: https://github.com/evilstreak/markdown-js, to avoid duplicate data entry.

If you'd like a hand, let me know. I build web apps/sites for a living. ;)

**Comment by iCHAIT** [comment]
I agree with @herrbischoff .

@seanoh1989 Maybe you should open a PR, and we can discuss it further, we definitely want to have a web page for the list sooner or later,  so I think it would be better to open a PR and discuss it then as to what kind of design we want and what kind of problems we may face.

What do you guys think?

**Comment by seanoh1989** [comment]
@herrbischoff Hi! Thanks for the awesome suggestion :+1: 

However, wouldn't the purpose of the website for people who really don't care about the GitHub page (non-geeky people)? and they wouldn't really be happy with super simple list based website because they do care about design over simplicity+usability. We could always make sample sites for both (bootstrap and markdown parser) and see which one suit more for our purpose.

Also if we do have bootstrap page, I will provide step-by-step tutorial about `how to create a product card and modal` so we have set template to prevent from the website going everywhere.

**Comment by herrbischoff** [comment]
I agree with @iCHAIT. Further discussion makes sense within a PR where we can directly comment on the code. We should work in a separate branch though. Possibly it makes sense that you create it, so we can all check out that branch to review and work on it. Naming suggestion: "website-dev"

Since it was @seanoh1989's idea, I believe he should initiate the PR. ;)

**Comment by seanoh1989** [comment]
@iCHAIT @herrbischoff 

Sorry but I'm pretty new to GitHub opensource projects so I need to catch up some abbreviations and conventions. Do you mean PR as Public Repo ? or Pull Request?  :sob:

**Comment by dufferzafar** [comment]
@seanoh1989 Pull Request. 

You don't have to be sorry for anything, by the way. We all learn something daily. :)

**Comment by herrbischoff** [comment]
@seanoh1989: no sweat. It means Pull Request. Ever done that before?

**Comment by seanoh1989** [comment]
No, I haven't. I'm trying to follow this example, but it looks like the owner @iCHAIT  has to create a branch ? Help me out haha

You guys are awesome :+1:

**Comment by herrbischoff** [comment]
I believe the easiest way is indeed for @iCHAIT to create a branch. You then fork the repository and clone it locally. Then create a new local branch from that branch and check that out. On the shell you do that with `git checkout -b <WEBSITE BRANCH> <YOUR BRANCH>`. It will be easiest if you use GitHub desktop for the time being, it makes this simple. You then work and commit in your branch and click on the button on the top right to create a pull request. Make sure that it points from your local branch to the original branch.

I know this probably sounds quite perplexing but especially in GitHub Desktop it should become self-explanatory after a few tries. Remember, if you mess up, you can always delete the cloned repo and start fresh. :)

**Comment by seanoh1989** [comment]
Yes I already cloned the project and made a new branch named `website-dev` under origin. 

I just need to push it but obviously I don't have permission to push it to non-existing branch on the repo :) I'll be waiting! 

Btw I use github and/or svn daily so basic stuff like clone,push/pull,add/delete/commit/ etc is fine with me. Thank you again!

**Comment by seisfeld** [comment]
@seanoh1989 You won't be able to push because you don't have write access to origin. You need to initiate a pull request and after discussion @iCHAIT will decide if he merges your branch or not.

**Comment by seanoh1989** [comment]
@iCHAIT  any update on this? Thanks!

**Comment by iCHAIT** [comment]
@seanoh1989 Sorry for getting such a delay, was really busy for the past few days, I think you should proceed with this and open a PR :+1:

**Comment by seanoh1989** [comment]
@iCHAIT can you make a new branch so I can do a PR ?

**Comment by iCHAIT** [comment]
@seanoh1989  Created a new branch `web-page` -

 https://github.com/iCHAIT/awesome-osx/tree/web-page

I hope this should get you going.

**Comment by seanoh1989** [comment]
@iCHAIT  PR created

**Comment by herrbischoff** [comment]
@seanoh1989: Any progress with this?

**Comment by seanoh1989** [comment]
@herrbischoff the PR has been made, but as I mentioned in the PR, I am having a busy month from my work :'( I'll get back to it as soon as this work gets a little bit lighter! :+1:

**Comment by herrbischoff** [comment]
@seanoh1989: Since it's been over two months since you declared your interest in building a front end but nothing happened, I just went ahead and built a possible technical foundation. Please see PR #203 for details.

Also, @iCHAIT: please check it out. :)
