### ISSUE TITLE
Textual 5 is now Open Source

### ISSUE THREAD

**Issue by miguelpalazzo** [iCHAIT/awesome-osx#34]
Just a head up, Applications > Chat Clients > Textual 5 is not Open Source, at all. It might confuse others as it happened to me.

**Comment by iCHAIT** [comment]
Wait, what?

I think it is open source - 
https://github.com/Codeux-Software/Textual

:\

**Comment by miguelpalazzo** [comment]
Sorry had a typo in the title! @iCHAIT You are right, however their link points to a trial option only, so it was misleading. Sorry for the confusion.

**Comment by iCHAIT** [comment]
No problem.

**Comment by nclements** [comment]
I had the same thought when I first saw the open source icon and it took me a bit of time to find the repo. Maybe a second link pointing to the source would be good?

**Comment by iCHAIT** [comment]
Yeah, I am thinking that for a while now, it is a tricky situation to be in because it is not just about textual, many of the apps on the list are open source though the url points to their website. Adding two links would make things a bit messy in `README` I believe but at the same time not specifying the link to the codebase (if open source) is also not a good idea.

**Comment by iCHAIT** [comment]
@dufferzafar What are your thoughts on this?

**Comment by dufferzafar** [comment]
I think that most of the repos on Github do contain a link to the website (but the websites might not have links to Github repos.) I feel we should prefer Github links.

**Comment by miguelpalazzo** [comment]
Totally agree with @dufferzafar

**Comment by iCHAIT** [comment]
Yeah that sounds good, BTW I was wondering if we could have a workaround for following - 

For all open source applications we point the primary link to the main website and link the OSS symbol to the source code of that application?
