### ISSUE TITLE
Please remove non open source software from the list

### ISSUE THREAD

**Issue by Emasoft** [iCHAIT/awesome-osx#62]
Good initiative, but this is GitHub, an open source community. You should not advertise non open source software. It is a lack of respect toward all people working hard for helping the community and sharing their code. Please remove all non open source apps from the list. There is already the Mac app store for those who do not believe in openess and sharing. For almost every one of the non open source apps listed there is an equivalent open source one if you search for it. Thanks.

**Comment by jaimehrubiks** [comment]
I do not agree. I love open source software, but that doesn't mean that we shouldn't use commercial software, which for me is in many case respectable.

**Comment by esttorhe** [comment]
What!? As far as I understand this is a list of great tools; not «great opensource tools».

>It is a lack of respect toward all people working hard for helping the community
What????

I seriously am missing the point here; why is sharing a list of tools the OP thinks are great a lack of respect??

I for one think this issue should be closed because I don't think is adding any value; perhaps maybe section the list into OSS and non OSS apps but removing non OSS doesn't make any sense TBH

**Comment by dufferzafar** [comment]
@iCHAIT I totally agree with @esttorhe in that this issue should be closed. Nothing more to say.
